const fs = require('fs');
const c = fs.readFileSync('C:/Users/BIG D/.openclaw/workspace/ezy-life-index.html', 'utf8');
console.log('Has modal-addfin:', c.includes('modal-addfin'));
console.log('Has fin-tab-ietc:', c.includes('fin-tab-ietc'));
console.log('Has fin-tab-bn1:', c.includes('fin-tab-bn1'));
console.log('Has fin-tab-bn2:', c.includes('fin-tab-bn2'));
console.log('Has ietc tab:', c.includes("'ietc'"));
console.log('Has fin-acct-type:', c.includes('fin-acct-type'));
console.log('Has emojis:', /[\u{1F000}-\u{1FFFF}]/u.test(c));
console.log('Has debug alerts:', c.includes("alert('DEBUG"));
console.log('File size:', c.length);
